services:
  - type: web
    name: mine-hr
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production